#Modify only PROJECT AND APP_FOLDER for your application

#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ../..

#filename of outputed .elf and .bin files
PROJECT = printf_out

#the folder the current app is in
#HAS TO BE THE SAME NAME AS THE FOLDER THIS IS IN
APP_FOLDER = printf

include $(BASE_PATH)/makefile